services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Taketool\Sysinfo\:
    resource: '../Classes/*'

  Taketool\Sysinfo\Controller\CurlController:
    public: true
    arguments:
      - '@Psr\Http\Message\ResponseFactoryInterface'
