services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Taketool\Sysinfo\Controller\CheckRemotePageController:
    arguments:
      - '@Psr\Http\Message\ResponseFactoryInterface'
